[request_definition]
r = sub, obj, act, brand, market, platform, shop, category, field

[policy_definition]
p = sub, obj, act, brand, market, platform, shop, category, field, eft

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (p.sub == r.sub || p.sub == "*") && (p.obj == r.obj || p.obj == "*") && (p.act == r.act || p.act == "*") && (p.brand == r.brand || p.brand == "*") && (p.market == r.market || p.market == "*") && (p.platform == r.platform || p.platform == "*") && (p.shop == r.shop || p.shop == "*") && (p.category == r.category || p.category == "*") && (p.field == r.field || p.field == "*")
