export const LISTING_GENERATION_SERVICE = Symbol('LISTING_GENERATION_SERVICE');
export const MCP_TOOL_CALL_SERVICE = Symbol('MCP_TOOL_CALL_SERVICE');
export const STRUCTURED_EXTRACTION_SERVICE = Symbol('STRUCTURED_EXTRACTION_SERVICE');
